config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # resources :cars, only: :index
  resources :cars, except: :destroy do
    resources :bookings, only: %i[new create edit update]
  end
  resources :bookings, only: %i[destroy index]
  resources :cars, only: :destroy
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :initial, :final, presence: true
  validate :validate_created_at

  private

  def validate_created_at
    self.initial >= Date.today
  end
end

app/models/car.rb
class Car < ApplicationRecord
  validates :brand, :year, :color, :model, :plate, :price, presence: true
  validates :year, :price, numericality: { only_integer: true }
  validates :year, numericality: { less_than_or_equal_to: 2022 }
  has_many_attached :photos

  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :cars, through: :bookings
  has_many :cars, foreign_key: "user_id"
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).where(user: current_user)
  end

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
    authorize @car
    authorize @booking
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    @booking.accepted = false
    authorize @car
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = booking.find(params[:id])
  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:initial, :final, :accepted)
  end
end

app/controllers/cars_controller.rb
require 'open-uri'

class CarsController < ApplicationController
  before_action :set_car, only: %i[edit update destroy]
  def index
    @cars = policy_scope(Car)
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.owner = current_user
    authorize @car
    if @car.save
      if @car.photos.attached?
        redirect_to cars_path
      else
        file = URI.open("https://www.clasificadoscontacto.com/_nuxt/img/auto-placeholder.84bcc3a.jpeg")
        @car.photos.attach(io: file, filename: "placeholder", content_type: "image/png")
        @car.save
        redirect_to cars_path
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @car = Car.find(params[:id])
    authorize @car
  end

  def edit

  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path, status: :see_other
    authorize @car
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:brand, :year, :color, :model, :plate, :price, {photos: []})
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h3>Your bookings</h3>
      <% @bookings.each do |booking| %>
        <div class="booking">
        <h5 class="booking-title" >Booking: <%= booking.car.brand %> <%= booking.car.model %></h5>
        <div >
          <h5><strong> Initial: <%= booking.initial %></strong></h5>
          <h5><strong> Final: <%= booking.final %></strong></h5>
          <br>
          <p>All the information</p>
          <ul>
            <li><%= booking.car.brand %></li>
            <li><%= booking.car.model %></li>
            <li><%= booking.car.color %></li>
            <li><%= booking.car.year %></li>
            <li class="info-booking-card"><%= booking.car.plate %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h3>Create a new booking</h3>
      <%= simple_form_for [@car, @booking] do |f| %>
        <%= f.input :initial, as: :date, label: 'Initial date' %>
        <%= f.input :final, as: :date, label: 'Final date' %>

        <%= f.submit class: 'btn brand-color' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/edit.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h3>Edit your car</h3>
      <%= simple_form_for @car do |f| %>
        <%= f.input :brand, placeholder: 'Audi' %>
        <%= f.input :year, placeholder: '2019' %>
        <%= f.input :color, placeholder: 'White' %>
        <%= f.input :model, placeholder: 'A3' %>
        <%= f.input :plate, placeholder: 'R3NT4R1DE' %>
        <%= f.input :price, placeholder: 'Price per day' %>

        <%= f.submit class: 'btn brand-color' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="cars-header-index">
  <h2>Cars available for rent</h2>
</div>
  <div class="cars-list">
    <% @cars.each do |car| %>
      <div class="card m-2" style="width: 18rem;">
        <%= cl_image_tag car.photos.first.key %>
        <div class="card-body">
          <h5 class="card-title"><%= car.brand%> <%= car.model %></h5>
          <p class="card-text"><%= car.year%></p>
          <p class="card-text">$<%= car.price %> p/d</p>
          <%= link_to "View more", car, class: "btn brand-color" %>
          <% if policy(car).edit? %>
            <%= link_to "Edit", edit_car_path(car), class: "btn btn-secondary" %>
          <% end %>
          <% if policy(car).destroy? %>
            <%= link_to "Remove", car_path(car), class:"text-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/cars/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h3>Post your car for rent</h3>
      <%= simple_form_for @car do |f| %>
        <%= f.input :brand, placeholder: 'Audi' %>
        <%= f.input :year, placeholder: '2019' %>
        <%= f.input :color, placeholder: 'White' %>
        <%= f.input :model, placeholder: 'A3' %>
        <%= f.input :plate, placeholder: 'R3NT4R1DE' %>
        <%= f.input :price, placeholder: 'Price per day' %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>


        <%= f.submit class: 'btn brand-color' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="show-car">
  <div class="car-info">
    <div class="car-header">
      <h1><%= @car.brand %> <%= @car.model %> <%= @car.year %></h1>
    </div>
    <div class="car-ul">
      <ul>
        <li>Color: <%= @car.color %></li>
        <li>Plate: <%= @car.plate %></li>
      </ul>
    </div>
    <div class="car-price">
      <h4>$<%= @car.price %> p/d</h4>
    </div>
    <div class="car-button">
      <% unless policy(@car).edit? %>
        <%= link_to "Book this car", new_car_booking_path(@car) %>
      <% end %>
    </div>
    <div class="car-conditions">
      <a href="#">Terms and conditions</a>
      <a href="#">Requirements</a>
    </div>
  </div>
  <div class="car-image">
    <% @car.photos.each do |photo| %>
      <%= cl_image_tag photo.key %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent-a-Ride</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'https://res.cloudinary.com/luda9/image/upload/v1661290604/favicon_azkwsu.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
  <div class="home-page">
    <h1 class="title">Premium car rental</h1>
    <p>Skip the rental car counter — Book exotic and luxury car rentals near you from trusted,
    local hosts on Rent a Ride, the world's largest car sharing marketplace.</p>
    <%= link_to "Get Started", cars_path, class:"home-button" %>
  </div>
    <img src="https://res.cloudinary.com/luda9/image/upload/v1661359725/van1_tmlt0j.png" alt="van1" class="van chevrolet">
    <img src="https://res.cloudinary.com/luda9/image/upload/v1661359725/van2_agfcs1.png" alt="van2" class="van cadillac">
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="nav-bar">
  <div class="container-fluid">
    <%= link_to  root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/luda9/image/upload/v1661283064/IMG_6325_mvoyk8.png", style:'width:50px;'%>
    <% end %>
      <%= link_to "Rent a ride", cars_path, class:"text-decoration-none text-secondary" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
          <%= link_to current_user.first_name.capitalize , edit_user_registration_path, class: "nav-link" %>
      <% end %>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cars", cars_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Promote", new_car_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/luda9", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-user">
  <div class="user-info">
    <div class="user-header">
    <div class="container">
      <h1><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h1>
    <div class="user-ul">
      <ul>
        <li>First name: <%= @user.first_name.capitalize %></li>
        <li>Last name: <%= @user.last_name.capitalize %></li>
      </ul>
    </div>
  </div>
  <div class="user-image">
    <% @user.photo.key %>
  </div>
    </div>
    </div>
</div>